config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'frontend#index'
  get 'frontend/index'

  resources :users
  post 'users/:id/accept_invitation' => 'users#accept_invitation', as: 'user_accept_invitation'
  post 'users/:id/reject_invitation' => 'users#reject_invitation', as: 'user_reject_invitation'
  get 'users/:id/invitations' => 'users#invitations', as: 'user_invitations'
  get 'users/:id/groups' => 'users#groups', as: 'user_groups'
  post 'users/:id/ban_group' => 'users#ban_group', as: 'user_ban_group'
  post 'users/login' => 'users#login', as: 'user_login'
  post 'users/logout' => 'users#logout', as: 'user_logout'
  get 'users/:id/groups_leading' => 'users#groups_leading', as: 'user_groups_leading'
  post 'users/:id/leave_group' => 'users#leave_group', as: 'user_leave_group'
  get 'users/:id/previa_invitations' => 'users#previa_invitations', as: 'user_previa_invitations'
  get 'users/:id/inbox' => 'users#inbox', as: 'user_inbox'
  get 'users/:id/gallery' => 'users#gallery', as: 'user_gallery'
  get 'users/:id/edit_gallery' => 'users#edit_gallery', as: 'user_edit_gallery'
  get 'users/:id/notifications' => 'users#notifications', as: 'user_notifications'
  post 'users/:id/delete_notification' => 'users#delete_notification', as: 'user_delete_notification'
  

  resources :previa_groups
  post 'previa_groups/:id/invite_user' => 'previa_groups#invite_user', as: 'previa_group_invite_user'
  get 'previa_groups/:id/invitable_users' => 'previa_groups#invitable_users', as: 'previa_group_invitable_users'
  post 'previa_groups/:id/ban_group' => 'previa_groups#ban_group', as: 'previa_group_ban_group'
  post 'previa_groups/:id/invite_group' => 'previa_groups#invite_group', as: 'previa_group_invite_group'
  post 'previa_groups/:id/accept_previa_invitation' => 'previa_groups#accept_previa_invitation', as: 'previa_group_accept_previa_invitation'
  post 'previa_groups/:id/reject_previa_invitation' => 'previa_groups#reject_previa_invitation', as: 'previa_group_reject_previa_invitation'
  get 'previa_groups/:id/current_users' => 'previa_groups#current_users', as: 'previa_group_current_users'
  post 'previa_groups/:id/finish' => 'previa_groups#finish', as: 'previa_group_finish'
  get 'previa_groups/:id/details' => 'previa_groups#details', as: 'previa_group_details'
  get 'previa_groups/:id/search_previa_groups' => 'previa_groups#search_previa_groups', as: 'previa_group_search_previa_groups'
  get 'previa_groups/:id/inbox' => 'previa_groups#inbox', as: 'previa_group_inbox'
  get 'previa_groups/:id/chat' => 'previa_groups#chat', as: 'previa_group_chat'
  post 'previa_groups/:id/send_message' => 'previa_groups#send_message', as: 'previa_group_send_message'
  post 'previa_groups/:id/delete_user' => 'previa_groups#delete_user', as: 'previa_group_delete_user'

  resources :properties
end

app/models/previa_group.rb
class PreviaGroup < ApplicationRecord
  validates_presence_of :name, :date, :search_gender, :search_distance
  validates_uniqueness_of :name

  validates :search_min_age, presence: true, numericality: { greater_than_or_equal_to: 18, less_than_or_equal_to: 90 }
  validates :search_max_age, presence: true, numericality: { greater_than_or_equal_to: 18, less_than_or_equal_to: 90 }

  belongs_to :leader, :class_name => 'User'

  has_many :previa_group_properties
  has_many :properties, :through => :previa_group_properties

  has_many :messages
  
  has_and_belongs_to_many :chats, :class_name =>'Chat', :join_table => 'previa_groups_chats', :foreign_key => 'previa_group_id', :association_foreign_key => 'chat_id'

  #has_many :previa_groups_users
  #has_many :users, through: :previa_groups_users, :class_name => 'User'
  has_and_belongs_to_many :users, :class_name =>'User', :join_table => 'previa_groups_users', :foreign_key => 'previa_group_id', :association_foreign_key => 'user_id'
  #has_and_belongs_to_many :users

  has_and_belongs_to_many :invited_users, :class_name =>'User', :join_table => 'user_invitations', :foreign_key => 'previa_group_id', :association_foreign_key => 'user_id'

  has_and_belongs_to_many :banned_users, :class_name =>'User', :join_table => 'user_bans', :foreign_key => 'previa_group_id', :association_foreign_key => 'user_id'
  
  has_and_belongs_to_many :banned_groups, :class_name =>'PreviaGroup', :join_table => 'group_bans', :foreign_key => 'banning_group_id', :association_foreign_key => 'banned_group_id'

  has_and_belongs_to_many :matched_groups, :class_name =>'PreviaGroup', :join_table => 'group_matches', :foreign_key => 'inviter_group_id', :association_foreign_key => 'invited_group_id'
  
  has_many :previa_invitations_sent, :class_name =>'PreviaInvitation', :foreign_key => 'inviting_group_id'
  has_many :previa_invitations_received, :class_name =>'PreviaInvitation', :foreign_key => 'invited_group_id'

  GENDER_TYPES = ["Masculino", "Femenino", "Todos"]

  attr_accessor :search_gender, :search_distance, :search_min_age, :search_max_age


  def search_gender
    prop = previa_group_properties.select{ |p| p.property.name == 'gender' }
    prop = prop.first
    if(prop.nil? or prop.value.empty?)
      prop = "Todos"
    else
      prop = prop.value
    end
  end

  def search_distance
    prop = previa_group_properties.select{ |p| p.property.name == 'distance' }
    prop = prop.first
    if(prop.nil? or prop.value.empty?)
      prop = "20"
    else
      prop = prop.value
    end
  end

  def search_min_age
    prop = previa_group_properties.select{ |p| p.property.name == 'min_age' }
    prop = prop.first
    if(prop.nil? or prop.value.empty?)
      prop = "18"
    else
      prop = prop.value
    end
  end

  def search_max_age
    prop = previa_group_properties.select{ |p| p.property.name == 'max_age' }
    prop = prop.first
    if(prop.nil? or prop.value.empty?)
      prop = "90"
    else
      prop = prop.value
    end
  end

  def min_age
    members = users
    min = members.min_by { |m| m.age}
    min.age
  end

  def max_age
    members = users
    max = members.max_by { |m| m.age}
    max.age
  end

  def gender
    members = users
    counts = Hash.new(0)
    members.each{ |m| counts[m.gender] += 1}
    ans = "Todos"
    if (counts.length == 1)
      ans = counts.first.first
    end
    ans
  end
end

app/controllers/previa_groups_controller.rb
class PreviaGroupsController < ApplicationController
  before_action :set_previa_group, except: [:new, :create, :index]
  before_action :set_user

  # GET /previa_groups
  # GET /previa_groups.json
  def index
    @title = "Grupos"
    @previa_groups = PreviaGroup.all
  end

  # GET /previa_groups/1
  # GET /previa_groups/1.json
  def show
    @title = "Grupo " + @previa_group.name
  end

  # GET /previa_groups/new
  def new
    @title = "Nuevo grupo"
    @previa_group = PreviaGroup.new(:active => false, :leader => @user, :search_min_age => 18, :search_max_age => 60, :search_gender => 'Mixto', :search_distance => 30)
  end

  # GET /previa_groups/1/edit
  def edit
    @title = "Editar grupo"
  end

  # POST /previa_groups
  # POST /previa_groups.json
  def create
    @previa_group = CreatePreviaGroup.call(previa_group_params, @user)   

    respond_to do |format|
      if @previa_group.persisted?
        format.html { redirect_to previa_group_invitable_users_path(@previa_group), notice: 'El grupo de previa fue creado con éxito.' }
        format.json { render :invitable_users, status: :created, location: @previa_group }
      else
        format.html { render :new }
        format.json { render json: @previa_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /previa_groups/1
  # PATCH/PUT /previa_groups/1.json
  def update
    respond_to do |format|
      if @previa_group.update(previa_group_params)
        format.html { redirect_to @previa_group, notice: 'El grupo de previa fue modificado con éxito.' }
        format.json { render :show, status: :ok, location: @previa_group }
      else
        format.html { render :edit }
        format.json { render json: @previa_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /previa_groups/1
  # DELETE /previa_groups/1.json
  def destroy
    @previa_group.destroy
    respond_to do |format|
      format.html { redirect_to previa_groups_url, notice: 'El grupo de previa fue borrado con éxito.' }
      format.json { head :no_content }
    end
  end

  # GET /previa_groups/1/details
  # GET /previa_groups/1/details.json
  def details
    @title = "Detalles de grupo"
    @current_users = GetCurrentUsers.call(@previa_group)
  end

  # GET /previa_groups/1/invitable_users
  # GET /previa_groups/1/invitable_users.json
  def invitable_users
    @title = "Invitar usuario"
    @invitable_users = GetInvitableUsers.call(@previa_group)
  end

  # GET /previa_groups/1/current_users
  # GET /previa_groups/1/current_users.json
  def current_users
    @title = "Usuarios actuales"
    @current_users = GetCurrentUsers.call(@previa_group)
  end

  # POST /previa_groups/1/invite_user
  # POST /previa_groups/1/invite_user.json
  def invite_user
    invited_user = User.find(params[:user_id])
    InviteUser.call(@previa_group, invited_user)

    respond_to do |format|
      format.html { redirect_to previa_group_invitable_users_path(@previa_group), notice: 'El usuario fue invitado con éxito.' }
      format.json { head :no_content }
    end
  end

  # POST /previa_groups/1/finish
  # POST /previa_groups/1/finish.json
  def finish
    FinishPreviaGroup.call(@previa_group)

    respond_to do |format|
      format.html { redirect_to previa_group_current_users_path(@previa_group), notice: 'El grupo de previa fue cerrado con éxito.'}
      format.json {head :no_content}
    end
  end

  # GET /previa_groups/1/invite_group
  # GET /previa_groups/1/invite_group.json
  def search_previa_groups
    @title = "Buscar previa"
    @previa_groups_found = SearchPreviaGroups.call(@previa_group)
  end

  # POST /previa_groups/1/ban_group
  # POST /previa_groups/1/ban_group.json
  def ban_group
    banned_group = PreviaGroup.find(params[:previa_group_id])
    BanGroupFromGroup.call(@previa_group, banned_group)

    respond_to do |format|
      format.html { redirect_to @previa_group, notice: 'El grupo de previa fue bloqueado con éxito.' }
      format.json { head :no_content }
    end
  end

  # POST /previa_groups/1/invite_group
  # POST /previa_groups/1/invite_group.json
  def invite_group
    invited_group = PreviaGroup.find(params[:previa_group_id])
    InviteGroup.call(@previa_group, invited_group)

    respond_to do |format|
      format.html { redirect_to previa_group_search_previa_groups_path(@previa_group), notice: 'El grupo de previa fue invitado con éxito.' }
      format.json { head :no_content }
    end
  end

  # POST /previa_groups/1/accept_previa_invitation
  # POST /previa_groups/1/accept_previa_invitation.json
  def accept_previa_invitation
    previa_invitation = PreviaInvitation.find(params[:previa_invitation_id])
    AcceptPreviaInvitation.call(@previa_group, previa_invitation)

    respond_to do |format|
      format.html { redirect_to @previa_group, notice: 'La invitación fue aceptada con éxito.' }
      format.json { head :no_content }
    end
  end

  # POST /previa_groups/1/reject_previa_invitation
  # POST /previa_groups/1/reject_previa_invitation.json
  def reject_previa_invitation
    previa_invitation = PreviaInvitation.find(params[:previa_invitation_id])
    RejectPreviaInvitation.call(@previa_group, previa_invitation)

    respond_to do |format|
      format.html { redirect_to @previa_group, notice: 'La invitación fue rechazada con éxito.' }
      format.json { head :no_content }
    end
  end

  # GET /previa_groups/1/inbox
  # GET /previa_groups/1/inbox.json
  def inbox
    @title = "Conversaciones del grupo " + @previa_group.name
    @chats = GetChatsForPreviaGroup.call(@previa_group)
  end

  # GET /previa_groups/1/chat
  # GET /previa_groups/1/chat.json
  def chat
    @title = "Conversacion"
    @chats = GetChatsForPreviaGroup.call(@previa_group)
    @messages = GetMessagesForChat.call(Chat.find(params[:chat]))
  end

  # POST /previa_groups/1/send_message
  # POST /previa_groups/1/send_message.json
  def send_message
    chat = Chat.find(params[:chat])
    SendMessageToChat.call(@previa_group, chat, params[:message])

    respond_to do |format|
      format.html { redirect_to previa_group_chat_path(@previa_group, :chat => chat) }
      format.json { head :no_content }
    end
  end

  # POST /previa_groups/1/delete_user
  # POST /previa_groups/1/delete_user.json
  def delete_user
    deleted_user = User.find(params[:user_id])
    DeleteUserFromGroup.call(@previa_group, deleted_user)

    respond_to do |format|
      format.html { redirect_to previa_group_current_users_path(@previa_group), notice: 'El usuario fue eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_previa_group
      @previa_group = PreviaGroup.find(params[:id])
      # @previa_group = PreviaGroup.find_by(id: 253223)
    end

    def set_user
      # session[:current_user_id] = User.find_by(id: 298486374)
      @user = User.find(session[:current_user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def previa_group_params
      params.fetch(:previa_group, {})
      params.require(:previa_group).permit(:user_id, :name, :active, :date, :leader_id, :group_attributes, :members, :invited_users, :banned_users, :banned_groups, :matched_groups, :previa_invitations, :search_min_age, :search_max_age, :search_gender, :search_distance, :chat, :previa_group_id, :previa_invitation_id)
    end
end

app/helpers/previa_groups_helper.rb
module PreviaGroupsHelper
end

app/views/previa_groups/_form.html.erb
<%= form_for(@previa_group) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <% if @previa_group.errors[:name].any? %>
      <div class="form-group row vertical-align has-error">
      <% else %>
      <div class="form-group row vertical-align">
      <% end %>
        <div class="col-xs-3 col-form-label">
          <%= f.label :name, "Nombre" %>
        </div>
        <div class="col-xs-9">
          <%= f.text_field :name, class: "form-control" %>
          <% if @previa_group.errors[:name].any? %>
          <%= @previa_group.errors[:name].first %>
          <% end %>
        </div>
      </div>

      <% if @previa_group.errors[:search_min_age].any? %>
      <div class="form-group row vertical-align has-error">
      <% else %>
      <div class="form-group row vertical-align">
      <% end %>
        <div class="col-xs-3 col-form-label">
          <%= f.label :search_min_age, "Edad mínima" %>
        </div>
        <div class="col-xs-9">
          <%= f.text_field :search_min_age, class: "form-control" %>
          <% if @previa_group.errors[:search_min_age].any? %>
          <%= @previa_group.errors[:search_min_age].first %>
          <% end %>
        </div>
      </div>

      <% if @previa_group.errors[:search_max_age].any? %>
      <div class="form-group row vertical-align has-error">
      <% else %>
      <div class="form-group row vertical-align">
      <% end %>
        <div class="col-xs-3 col-form-label">
          <%= f.label :search_max_age, "Edad máxima" %>
        </div>
        <div class="col-xs-9">
          <%= f.text_field :search_max_age, class: "form-control" %>
          <% if @previa_group.errors[:search_max_age].any? %>
          <%= @previa_group.errors[:search_max_age].first %>
          <% end %>
        </div>
      </div>

      <% if @previa_group.errors[:search_gender].any? %>
      <div class="form-group row vertical-align has-error">
      <% else %>
      <div class="form-group row vertical-align">
      <% end %>
        <div class="col-xs-3 col-form-label">
          <%= f.label :search_gender, "Tipo de grupo" %>
        </div>
        <div class="col-xs-9">
          <%= f.select :search_gender, PreviaGroup::GENDER_TYPES, {prompt: "Seleccione sexo"}, {class: "form-control"} %>
          <% if @previa_group.errors[:search_gender].any? %>
          <%= @previa_group.errors[:search_gender].first %>
          <% end %>
        </div>
      </div>

      <% if @previa_group.errors[:search_distance].any? %>
      <div class="form-group row vertical-align has-error">
      <% else %>
      <div class="form-group row vertical-align">
      <% end %>
        <div class="col-xs-3 col-form-label">
          <%= f.label :search_distance, "Distancia" %>
        </div>
        <div class="col-xs-9">
          <%= f.text_field :search_distance, class: "form-control" %>
          <% if @previa_group.errors[:search_distance].any? %>
          <%= @previa_group.errors[:search_distance].first %>
          <% end %>
        </div>
      </div>
      <div class="actions">
      <%=tag("input", type: 'submit', class: "btn btn-primary", value: "Guardar", 'aria-label' => 'Guardar') %>
      </div>
    </div>
  </div>
<% end %>

app/views/previa_groups/chat.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2>Mensajes</h2>
  </div>
  <div class="panel-body panel-height">

  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
    <div class="row">
        <div class="conversation-wrap col-lg-4">
            <% @chats.each do |chat| %>
                <div class="media conversation">
                    <a class="pull-left" href="<%= previa_group_chat_path(@previa_group, :chat => chat) %>" >
                        <%= image_tag(chat.with(@previa_group).first.leader.image.thumb.url, :alt => "Imagen de perfil del líder") if chat.with(@previa_group).first.leader.image? %>
                    </a>
                    <div class="media-body">
                        <h3 class="media-heading"><%= chat.with(@previa_group).first.name %></h3>
                        <p><%= chat.messages.last.message %></p>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="message-wrap col-lg-8">
            <div class="msg-wrap">
              <% @messages.each do |message| %>
                <div class="media msg ">
                    <div class="pull-left">
                      <%= image_tag(message.author.leader.image.thumb.url, :alt => "Imagen de perfil del líder") if message.author.leader.image? %>
                    </div>
                    <div class="media-body">
                        <p class="pull-right time"><em class="fa fa-clock-o"></em><%= message.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
                        <h3 class="media-heading"><%= message.author.name %></h3>
                        <p class="col-lg-10"><%= message.message %></p>
                    </div>
                </div>
                <!-- <div class="alert alert-info msg-date">
                    <strong>Today</strong>
                </div> -->
              <% end %>
            </div>

            <%= form_for :previa_groups, url: url_for( :controller => :previa_groups, :action => :send_message, :method => :post ) do |f| %>
              <%= hidden_field_tag :chat, @messages.first.chat.id %>
              <div class="send-wrap ">
                  <label class="sr-only" for="message">Mensaje</label>
                  <textarea class="form-control send-message" id="message" name="message" rows="3" placeholder="Escribir..."></textarea>
              </div>
              <div>
                <%=tag("input", type: 'submit', class: "col-lg-3 pull-right btn btn-success", value: "Enviar".html_safe, 'aria-label' => 'Enviar') %>
              </div>
            <% end %>
        </div>
    </div>
  </div>
</div>

app/views/previa_groups/current_users.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de usuarios del grupo <%= @previa_group.name %></h1>
  </div>
  <div class="panel-body">
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>


    <table class="table table-bordered" aria-labelledby="tabla-usuarios-actuales">
      <caption class="sr-only" id="tabla-usuarios-actuales">Lista de usuarios que pertenecen a un grupo</caption>
      <thead>
        <tr>
          <th id="columna_foto">Foto</th>
          <th id="columna_nombre">Nombre</th>
          <th id="columna_apellido">Apellido</th>
          <th id="columna_edad">Edad</th>
          <th id="columna_ciudad">Ciudad</th>
          <% if @user == @previa_group.leader%>
          <th id="columna_acciones">Acciones</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @current_users.each do |user| %>
          <tr>
            <td headers="columna_foto"><%= image_tag(user.image.thumb.url, :alt => "Imagen de perfil del usuario") if user.image?%></td>
            <td headers="columna_nombre"><%= user.first_name %></td>
            <td headers="columna_apellido"><%= user.last_name %></td>
            <td headers="columna_edad"><%= user.age %></td>
            <td headers="columna_ciudad"><%= user.city.name %></td>
            <% if @user == @previa_group.leader and @user != user %>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-close fa-lg' aria-hidden='true'></span> Eliminar".html_safe, previa_group_delete_user_path(@previa_group, :user_id => user.id), method: :post, data: { confirm: '¿Estás seguro?'}, class: "btn btn-danger" %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Atrás', user_groups_path(), class: 'btn btn-info' %>
  </div>
</div>

app/views/previa_groups/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Editar grupo</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/previa_groups/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de grupos</h1>
  </div>
  <div class="panel-body">
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  
    <table aria-labelledby="tabla-grupos">
      <caption class="sr-only" id="tabla-grupos">Lista de grupos</caption>
      <thead>
        <tr>
          <th id="columna_nombre">Nombre</th>
          <th id="columna_lider">Lider</th>
          <th id="columna_activo">Activo</th>
          <th id="columna_fecha">Fecha</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @previa_groups.each do |previa_group| %>
          <tr>
            <td headers="columna_nombre"><%= previa_group.name %></td>
            <td headers="columna_lider"><%= previa_group.leader.first_name %></td>
            <td headers="columna_activo"><%= previa_group.active %></td>
            <td headers="columna_fecha"><%= previa_group.date %></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Mostrar <span class='sr-only' aria-hidden='true'>grupo #{previa_group.name}</span>".html_safe,previa_group, class: "btn btn-success" %>
              <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Editar <span class='sr-only' aria-hidden='true'>grupo #{previa_group.name}</span>".html_safe, edit_previa_group_path(previa_group), class: "btn btn-primary" %>
              <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Eliminar <span class='sr-only' aria-hidden='true'>grupo #{previa_group.name}</span>".html_safe, previa_group, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/previa_groups/invitable_users.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de usuarios a invitar</h1>
  </div>
  <div class="panel-body">
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

    <table class="table table-bordered" aria-labelledby="tabla-usuarios-invitables">
      <caption class="sr-only" id="tabla-usuarios-invitables">Lista de usuarios a invitar</caption>
      <thead>
        <tr>
          <th id="columna_nombre">Nombre</th>
          <th id="columna_apellido">Apellido</th>
          <th id="columna_mail">Mail</th>
          <th id="columna_ciudad">Ciudad</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @invitable_users.each do |user| %>
          <tr>
            <td headers="columna_nombre"><%= user.first_name %></td>
            <td headers="columna_apellido"><%= user.last_name %></td>
            <td headers="columna_mail"><%= user.email %></td>
            <td headers="columna_ciudad"><%= user.city.name %></td>
            <td  headers="columna_acciones">
              <%= link_to "<span class='fa fa-check fa-lg' aria-hidden='true'></span> Invitar".html_safe, previa_group_invite_user_path(@previa_group, :user_id => user.id), method: :post, data: { confirm: '¿Estás seguro?'}, class: "btn btn-success" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/previa_groups/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Nuevo grupo</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/previa_groups/search_previa_groups.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de grupos encontrados</h1>
  </div>
  <div class="panel-body">
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  
    <table class="table table-bordered" aria-labelledby="tabla-previas">
      <caption class="sr-only" id="tabla-previas">Lista de los grupos que coincidieron con los parámetros de búsqueda</caption>
      <thead>
        <tr>
          <th id="columna_nombre">Nombre</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @previa_groups_found.each do |previa_group| %>
          <tr>
            <td headers="columna_nombre"><%= previa_group.name %></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Detalles <span class='sr-only' aria-hidden='true'>de grupo #{previa_group.name}</span>".html_safe,previa_group_details_path(previa_group), class: "btn btn-info" %>
              <%= link_to "<span class='fa fa-check fa-lg' aria-hidden='true'></span> Invitar <span class='sr-only' aria-hidden='true'>al grupo #{previa_group.name}</span>".html_safe,previa_group_invite_group_path(@previa_group, :previa_group_id => previa_group), method: :post, data: { confirm: '¿Estás seguro?' }, class: "btn btn-success" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>