config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'frontend#index'
  get 'frontend/index'

  resources :users
  post 'users/:id/accept_invitation' => 'users#accept_invitation', as: 'user_accept_invitation'
  post 'users/:id/reject_invitation' => 'users#reject_invitation', as: 'user_reject_invitation'
  get 'users/:id/invitations' => 'users#invitations', as: 'user_invitations'
  get 'users/:id/groups' => 'users#groups', as: 'user_groups'
  post 'users/:id/ban_group' => 'users#ban_group', as: 'user_ban_group'
  post 'users/login' => 'users#login', as: 'user_login'
  post 'users/logout' => 'users#logout', as: 'user_logout'
  get 'users/:id/groups_leading' => 'users#groups_leading', as: 'user_groups_leading'
  post 'users/:id/leave_group' => 'users#leave_group', as: 'user_leave_group'
  get 'users/:id/previa_invitations' => 'users#previa_invitations', as: 'user_previa_invitations'
  get 'users/:id/inbox' => 'users#inbox', as: 'user_inbox'
  get 'users/:id/gallery' => 'users#gallery', as: 'user_gallery'
  get 'users/:id/edit_gallery' => 'users#edit_gallery', as: 'user_edit_gallery'
  get 'users/:id/notifications' => 'users#notifications', as: 'user_notifications'
  post 'users/:id/delete_notification' => 'users#delete_notification', as: 'user_delete_notification'
  

  resources :previa_groups
  post 'previa_groups/:id/invite_user' => 'previa_groups#invite_user', as: 'previa_group_invite_user'
  get 'previa_groups/:id/invitable_users' => 'previa_groups#invitable_users', as: 'previa_group_invitable_users'
  post 'previa_groups/:id/ban_group' => 'previa_groups#ban_group', as: 'previa_group_ban_group'
  post 'previa_groups/:id/invite_group' => 'previa_groups#invite_group', as: 'previa_group_invite_group'
  post 'previa_groups/:id/accept_previa_invitation' => 'previa_groups#accept_previa_invitation', as: 'previa_group_accept_previa_invitation'
  post 'previa_groups/:id/reject_previa_invitation' => 'previa_groups#reject_previa_invitation', as: 'previa_group_reject_previa_invitation'
  get 'previa_groups/:id/current_users' => 'previa_groups#current_users', as: 'previa_group_current_users'
  post 'previa_groups/:id/finish' => 'previa_groups#finish', as: 'previa_group_finish'
  get 'previa_groups/:id/details' => 'previa_groups#details', as: 'previa_group_details'
  get 'previa_groups/:id/search_previa_groups' => 'previa_groups#search_previa_groups', as: 'previa_group_search_previa_groups'
  get 'previa_groups/:id/inbox' => 'previa_groups#inbox', as: 'previa_group_inbox'
  get 'previa_groups/:id/chat' => 'previa_groups#chat', as: 'previa_group_chat'
  post 'previa_groups/:id/send_message' => 'previa_groups#send_message', as: 'previa_group_send_message'
  post 'previa_groups/:id/delete_user' => 'previa_groups#delete_user', as: 'previa_group_delete_user'

  resources :properties
end

app/views/partials/_footer.html.erb
<footer>
  <p>&copy; 2016 PintaPreva</p>
</footer>

app/views/partials/_sidenav_admin.html.erb
<ul class="nav nav-sidebar">
  <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
  <li><a href="#">Reports</a></li>
</ul>
<ul class="nav nav-sidebar">
  <li><a href="">Nav item</a></li>
</ul>
<ul class="nav nav-sidebar">
  <li><a href="">Nav item again</a></li>
</ul>

app/views/partials/_sidenav_user.html.erb
<div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="visible-xs navbar-brand">Menú</span>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="list-group">
        <li class="nav-header disabled"><a>Grupo</a></li>
        <li class="<% if current_page?(new_previa_group_path)%>active<% end %> list-group-item">
          <% if current_page?(new_previa_group_path)%>
            <%= link_to "<span class='sr-only'>(actual)</span>Crear grupo".html_safe, new_previa_group_path%>
          <%else%>
            <%= link_to "Crear grupo".html_safe, new_previa_group_path%>
          <%end%> 
        </li>
        <li class="<% if current_page?(user_groups_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_groups_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Listar grupos".html_safe, user_groups_path(@user)%>
          <%else%>
            <%= link_to "Listar grupos".html_safe, user_groups_path(@user)%>
          <%end%> 
        </li>
        <li class="<% if current_page?(user_groups_leading_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_groups_leading_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Administrar grupos".html_safe, user_groups_leading_path(@user)%>
          <%else%>
            <%= link_to "Administrar grupos".html_safe, user_groups_leading_path(@user)%>
          <%end%> 
        </li>
        <li class="<% if current_page?(user_invitations_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_invitations_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Invitaciones a grupo".html_safe, user_invitations_path(@user) %>
          <%else%>
            <%= link_to "Invitaciones a grupo".html_safe, user_invitations_path(@user) %>
          <%end%>  
        </li>
        <li class="<% if current_page?(user_previa_invitations_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_previa_invitations_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Solicitudes de previa".html_safe, user_previa_invitations_path(@user) %>
          <%else%>
            <%= link_to "Solicitudes de previa".html_safe, user_previa_invitations_path(@user) %>
          <%end%>  
        </li>
      </ul>
      <ul class="list-group">
        <li class="<% if current_page?(user_inbox_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_inbox_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Bandeja de entrada".html_safe, user_inbox_path(@user)%>
          <%else%>
            <%= link_to "Bandeja de entrada".html_safe, user_inbox_path(@user)%>
          <%end%>  
        </li>
        <li class="<% if current_page?(user_notifications_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_notifications_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Notificaciones".html_safe, user_notifications_path(@user)%>
          <%else%>
            <%= link_to "Notificaciones".html_safe, user_notifications_path(@user)%>
          <%end%>
        </li>
      </ul>
      <ul class="list-group">
        <li class="nav-header disabled"><a>Cuenta</a></li>
        <li class="<% if current_page?(edit_user_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(edit_user_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Editar perfil".html_safe, edit_user_path(@user) %>
          <%else%>
            <%= link_to "Editar perfil".html_safe, edit_user_path(@user) %>
          <%end%>
        </li>
        <% if false %>
        <li class="<% if current_page?(user_gallery_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_gallery_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Ver galeria".html_safe, user_gallery_path(@user) %>
          <%else%>
            <%= link_to "Ver galeria".html_safe, user_gallery_path(@user) %>
          <%end%>
        </li>
        <li class="<% if current_page?(user_edit_gallery_path(@user))%>active<% end %> list-group-item">
          <% if current_page?(user_edit_gallery_path(@user))%>
            <%= link_to "<span class='sr-only'>(actual)</span>Editar galeria".html_safe, user_edit_gallery_path(@user) %>
          <%else%>
            <%= link_to "Editar galeria".html_safe, user_edit_gallery_path(@user) %>
          <%end%>
        </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/partials/_topnav.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Pinta Previa</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Mail" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Clave" class="form-control">
            </div>
            <!--<button type="submit" class="btn btn-success">Ingresar</button>-->
            <%= link_to 'Ingresar', users_path, class: 'btn btn-success btn-md' %>

          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

app/views/partials/_topnav_login.html.erb
      <div class=navbar-header>
        <button aria-controls=bs-navbar aria-expanded=false class="collapsed navbar-toggle" data-target=#bs-navbar data-toggle=collapse type=button>
        <span class=sr-only>Toggle navigation</span>
        <span class=icon-bar></span>
        <span class=icon-bar></span>
        <span class=icon-bar></span>
        </button>
        <h1>
          <%= image_tag("pintaprevia.jpg", :alt => "Logo del sistema", height: '50', width: '50') %><span class="label">Pinta Previa</span>
        </h1>
      </div>
      <nav class="collapse navbar-collapse" id=bs-navbar>
        <ul class="nav navbar-nav navbar-right">
          <%= form_for :users, url: url_for( :controller => :users, :action => :login ), :html => {:class => "navbar-form navbar-right"} do |f| %>
            <div class="form-group">  
              <label class="sr-only" for="email">Mail</label>
              <input type="text" id="email" name="email" placeholder="Mail" class="form-control">
            </div>
            <div class="form-group">
              <label class="sr-only" for="pass">Clave</label>
              <input type="password" id="pass" name="pass" placeholder="Clave" class="form-control">
            </div>
            <%=tag("input", type: 'submit', class: "btn btn-success btn-md", value: "Ingresar", 'aria-label' => 'Ingresar') %>
          <% end %>
        </ul>
      </nav>

app/views/partials/_topnav_logout.html.erb
      <div class=navbar-header>
        <button aria-controls=bs-navbar aria-expanded=false class="collapsed navbar-toggle" data-target=#bs-navbar data-toggle=collapse type=button>
        <span class=sr-only>Toggle navigation</span>
        <span class=icon-bar></span>
        <span class=icon-bar></span>
        <span class=icon-bar></span>
        </button>
        <h1>
          <%= image_tag(@user.image.thumb.url, :alt => "Imagen de perfil del usuario") if @user.image? %><span class="label"><%= @user.first_name%></span>
        </h1>
      </div>
      <nav class="collapse navbar-collapse" id=bs-navbar>
        <ul class="nav navbar-nav">

          <li class="<% if current_page?(new_previa_group_path)%>active<% end %>">
            <% if current_page?(new_previa_group_path)%>
              <%= link_to "<span class='sr-only'>(actual)</span>Crear grupo".html_safe, new_previa_group_path%>
            <%else%>
              <%= link_to "Crear grupo".html_safe, new_previa_group_path%>
            <%end%> 
          </li>
          <li class="<% if current_page?(user_groups_path(@user))%>active<% end %>">
            <% if current_page?(user_groups_path(@user))%>
              <%= link_to "<span class='sr-only'>(actual)</span>Grupos".html_safe, user_groups_path(@user)%>
            <%else%>
              <%= link_to "Grupos".html_safe, user_groups_path(@user)%>
            <%end%> 
          </li>
          <li class="<% if current_page?(user_groups_leading_path(@user))%>active<% end %>">
            <% if current_page?(user_groups_leading_path(@user))%>
              <%= link_to "<span class='sr-only'>(actual)</span>Administrar".html_safe, user_groups_leading_path(@user)%>
            <%else%>
              <%= link_to "Administrar".html_safe, user_groups_leading_path(@user)%>
            <%end%> 
          </li>
          <li class="<% if current_page?(user_invitations_path(@user))%>active<% end %>">
            <% if current_page?(user_invitations_path(@user))%>
              <%= link_to "<span class='sr-only'>(actual)</span>Invitaciones".html_safe, user_invitations_path(@user) %>
            <%else%>
              <%= link_to "Invitaciones".html_safe, user_invitations_path(@user) %>
            <%end%>  
          </li>
          <li class="<% if current_page?(user_previa_invitations_path(@user))%>active<% end %>">
            <% if current_page?(user_previa_invitations_path(@user))%>
              <%= link_to "<span class='sr-only'>(actual)</span>Solicitudes de previa".html_safe, user_previa_invitations_path(@user) %>
            <%else%>
              <%= link_to "Solicitudes de previa".html_safe, user_previa_invitations_path(@user) %>
            <%end%>  
          </li>

          <li class="<% if current_page?(user_inbox_path(@user))%>active<% end %> ">
            <% if current_page?(user_inbox_path(@user))%>
              <%= link_to "<span class='sr-only'>(actual)</span>Mensajes".html_safe, user_inbox_path(@user)%>
            <%else%>
              <%= link_to "Mensajes".html_safe, user_inbox_path(@user)%>
            <%end%>  
          </li>
          <li class="<% if current_page?(user_notifications_path(@user))%>active<% end %>">
            <% if current_page?(user_notifications_path(@user))%>
              <%= link_to "<span class='sr-only'>(actual)</span>Notificaciones".html_safe, user_notifications_path(@user)%>
            <%else%>
              <%= link_to "Notificaciones".html_safe, user_notifications_path(@user)%>
            <%end%>
          </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li class="<% if current_page?(user_path(@user))%>active<% end %>">
            <% if current_page?(edit_user_path(@user))%>
              <%= link_to "<span class='sr-only'>(actual)</span>Perfil".html_safe, user_path(@user) %>
            <%else%>
              <%= link_to "Perfil".html_safe, user_path(@user) %>
            <%end%>
          </li>

          <li>
            <%= form_for :users, url: url_for( :controller => :users, :action => :logout ), :html => {:class => "navbar-form navbar-right"} do |f| %>
              <%=tag("input", type: 'submit', class: "btn btn-primary btn-md", value: "Cerrar sesión") %>
            <% end %>
          </li>
        </ul>
      </nav>