config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'frontend#index'
  get 'frontend/index'

  resources :users
  post 'users/:id/accept_invitation' => 'users#accept_invitation', as: 'user_accept_invitation'
  post 'users/:id/reject_invitation' => 'users#reject_invitation', as: 'user_reject_invitation'
  get 'users/:id/invitations' => 'users#invitations', as: 'user_invitations'
  get 'users/:id/groups' => 'users#groups', as: 'user_groups'
  post 'users/:id/ban_group' => 'users#ban_group', as: 'user_ban_group'
  post 'users/login' => 'users#login', as: 'user_login'
  post 'users/logout' => 'users#logout', as: 'user_logout'
  get 'users/:id/groups_leading' => 'users#groups_leading', as: 'user_groups_leading'
  post 'users/:id/leave_group' => 'users#leave_group', as: 'user_leave_group'
  get 'users/:id/previa_invitations' => 'users#previa_invitations', as: 'user_previa_invitations'
  get 'users/:id/inbox' => 'users#inbox', as: 'user_inbox'
  get 'users/:id/gallery' => 'users#gallery', as: 'user_gallery'
  get 'users/:id/edit_gallery' => 'users#edit_gallery', as: 'user_edit_gallery'
  get 'users/:id/notifications' => 'users#notifications', as: 'user_notifications'
  post 'users/:id/delete_notification' => 'users#delete_notification', as: 'user_delete_notification'
  

  resources :previa_groups
  post 'previa_groups/:id/invite_user' => 'previa_groups#invite_user', as: 'previa_group_invite_user'
  get 'previa_groups/:id/invitable_users' => 'previa_groups#invitable_users', as: 'previa_group_invitable_users'
  post 'previa_groups/:id/ban_group' => 'previa_groups#ban_group', as: 'previa_group_ban_group'
  post 'previa_groups/:id/invite_group' => 'previa_groups#invite_group', as: 'previa_group_invite_group'
  post 'previa_groups/:id/accept_previa_invitation' => 'previa_groups#accept_previa_invitation', as: 'previa_group_accept_previa_invitation'
  post 'previa_groups/:id/reject_previa_invitation' => 'previa_groups#reject_previa_invitation', as: 'previa_group_reject_previa_invitation'
  get 'previa_groups/:id/current_users' => 'previa_groups#current_users', as: 'previa_group_current_users'
  post 'previa_groups/:id/finish' => 'previa_groups#finish', as: 'previa_group_finish'
  get 'previa_groups/:id/details' => 'previa_groups#details', as: 'previa_group_details'
  get 'previa_groups/:id/search_previa_groups' => 'previa_groups#search_previa_groups', as: 'previa_group_search_previa_groups'
  get 'previa_groups/:id/inbox' => 'previa_groups#inbox', as: 'previa_group_inbox'
  get 'previa_groups/:id/chat' => 'previa_groups#chat', as: 'previa_group_chat'
  post 'previa_groups/:id/send_message' => 'previa_groups#send_message', as: 'previa_group_send_message'
  post 'previa_groups/:id/delete_user' => 'previa_groups#delete_user', as: 'previa_group_delete_user'

  resources :properties
end

app/models/user.rb
include CarrierWave::Validations::ActiveModel
class User < ApplicationRecord


  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates_processing_of :image
  validate :image_size_validation

  validates :pass, confirmation: true
  validates :pass_confirmation, presence: true
  validates :email, confirmation: true
  validates :email_confirmation, presence: true
  validates_presence_of :first_name, :last_name, :email, :pass, :birth_date, :gender, :city
  validates_uniqueness_of :email

  belongs_to :city, :class_name => 'City', inverse_of: 'users', :foreign_key => 'city_id'

  #has_many :previa_groups_users
  #has_many :previa_groups, through: :previa_groups_users, :class_name => 'PreviaGroup'
  has_and_belongs_to_many :previa_groups, :class_name=>'PreviaGroup', :join_table => 'previa_groups_users', :foreign_key => 'user_id', :association_foreign_key => 'previa_group_id'
  #has_and_belongs_to_many :previa_groups

  #has_many :user_invitations
  #has_many :invitations, through: :user_invitations, :class_name => 'PreviaGroup'
  has_and_belongs_to_many :invitations, :class_name=>'PreviaGroup', :join_table => 'user_invitations', :foreign_key => 'user_id', :association_foreign_key => 'previa_group_id'

  #has_many :user_bans
  #has_many :banned_groups, through: :user_bans, :class_name => 'PreviaGroup'
  has_and_belongs_to_many :banned_groups, :class_name=>'PreviaGroup', :join_table => 'user_bans', :foreign_key => 'user_id', :association_foreign_key => 'previa_group_id'
  
  has_many :notifications

  GENDER_TYPES = ["Masculino", "Femenino"]

  def age
    now = Time.now.utc.to_date
    now.year - birth_date.year - ((now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)) ? 0 : 1)
  end

  private
    def image_size_validation
      errors[:image] << "El tamaño del archivo debe ser menor que 500KB" if image.size > 0.5.megabytes
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action { flash.clear }
  before_action :set_user, :except => [:new, :login, :create]
  before_filter :authorize, :except => [:new, :login, :create]

  # GET /users
  # GET /users.json
  def index
    @title = "Usuarios"
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = "Usuario " + @user.first_name + " " + @user.last_name
  end

  # GET /users/new
  def new
    @title = "Nuevo usuario"
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @title = "Editar usuario"
  end

  # POST /users
  # POST /users.json
  def create
    @user = CreateUser.call(user_params)
    #@user = User.new(user_params)

    respond_to do |format|
      if @user.valid?
        #url_for(:controller => :frontend, :action => :index)
        format.html { redirect_to root_path, notice: 'El usuario fue creado con éxito.'}
        format.json { redirect_to root_path, status: :ok} #TODO
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'El usuario fue modificado con éxito.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'El usuario fue borrado con éxito.' }
      format.json { head :no_content }
    end
  end

  # POST /users/login
  # POST /users/login.json
  def login
    @user = AuthenticateUser.call(params[:email], params[:pass])
    respond_to do |format|
      if !@user.nil?
        session[:current_user_id] = @user.id
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to url_for(:controller => :frontend, :action => :index), notice: 'Mail y/o clave incorrectas.'}
        format.json { } #TODO
      end
    end
  end

  # POST /users/logout
  # POST /users/logout.json
  def logout
    session.delete(:current_user_id)
    
    respond_to do |format|
      format.html { redirect_to url_for(:controller => :frontend, :action => :index), notice: 'Se ha cerrado la sesión con éxito.'}
      format.json { head :no_content }
    end
  end
  
  # POST /users/1/accept_invitation
  # POST /users/1/accept_invitation.json
  def accept_invitation
    previa_group = PreviaGroup.find(params[:invitation_id])
    AcceptGroupInvitation.call(@user, previa_group)

    respond_to do |format|
      format.html { redirect_to @user, notice: 'La invitación fue aceptada con éxito.' }
      format.json { head :no_content }
    end
  end

  # POST /users/1/reject_invitation
  # POST /users/1/reject_invitation.json
  def reject_invitation
    previa_group = PreviaGroup.find(params[:invitation_id])
    RejectGroupInvitation.call(@user, previa_group)

    respond_to do |format|
      format.html { redirect_to @user, notice: 'La invitación fue rechazada con éxito.' }
      format.json { head :no_content }
    end
  end

  # GET /users/1/invitations
  # GET /users/1/invitations.json
  def invitations
    @title = "Invitaciones"
    @invitations = GetInvitationsForUser.call(@user)
  end

  # GET /users/1/previa_invitations
  # GET /users/1/previa_invitations.json
  def previa_invitations
    @title = "Invitaciones a previa"
    @previa_invitations = GetPreviaInvitations.call(@user)
  end

  # GET /users/1/groups
  # GET /users/1/groups.json
  def groups
    @title = "Grupos"
  end

  # GET /users/1/groups_leading
  # GET /users/1/groups_leading.json
  def groups_leading
    @title = "Administrar grupos"
    @groups_leading = GetGroupsLeading.call(@user)
  end

  # POST /users/1/ban_group
  # POST /users/1/ban_group.json
  def ban_group
    previa_group = PreviaGroup.find(params[:previa_group_id])
    BanGroupFromUser.call(@user, previa_group)

    respond_to do |format|
      format.html { redirect_to @user, notice: 'El grupo de previa fue bloqueado con éxito.' }
      format.json { head :no_content }
    end
  end

  # POST /users/1/leave_group
  # POST /users/1/leave_group.json
  def leave_group
    previa_group = PreviaGroup.find(params[:id])
    LeavePreviaGroup.call(@user, previa_group)

    respond_to do |format|
      format.html { redirect_to user_groups_path(@user), notice: 'El grupo de previa fue abandonado con éxito.' }
      format.json { head :no_content }
    end
  end

  # GET /users/1/inbox
  # GET /users/1/inbox.json
  def inbox
    @title = "Mensajes"
    @groups_leading = GetGroupsLeading.call(@user)
  end

  # GET /users/1/gallery
  # GET /users/1/gallery.json
  def gallery
    @title = "Galeria"
  end

  # GET /users/1/edit_gallery
  # GET /users/1/edit_gallery.json
  def edit_gallery
    @title = "Editar galeria"
  end

  # GET /users/1/notifications
  # GET /users/1/notifications.json
  def notifications
    @title = "Notificaciones"
    @notifications = GetNotificationsForUser.call(@user)
  end

  # POST /users/1/delete_notification
  # POST /users/1/delete_notification.json
  def delete_notification
    notification = Notification.find(params[:notification_id])
    DeleteNotification.call(@user, notification)

    respond_to do |format|
      format.html { redirect_to user_notifications_path(@user), notice: 'La notificacion fue eliminada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      # session[:current_user_id] = User.all.first.id
      @user = User.find_by(id: session[:current_user_id])
    end

    def authorize
      # session[:current_user_id] = 298486374
      if session[:current_user_id].nil?
        redirect_to(root_path)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:previa_group_id, :first_name, :last_name, :email, :email_confirmation, :pass, :pass_confirmation, :birth_date, :gender, :city_id, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Editar perfil</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_gallery.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Editar galería</h1>
  </div>
  <div class="panel-body">

  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

    <div class="col-sm-6" id="slider-thumbs">
        <!-- Bottom switcher of slider -->
        <ul class="hide-bullets">
            <li class="col-sm-3">
                <input type="checkbox" value="zero">
                <a class="thumbnail" id="carousel-selector-0"><img src="http://placehold.it/150x150&text=zero" alt=""></a>
            </li>
            <li class="col-sm-3">
                <input type="checkbox" value="one">
                <a class="thumbnail" id="carousel-selector-1"><img src="http://placehold.it/150x150&text=1" alt=""></a>
            </li>

            <li class="col-sm-3">
                <input type="checkbox" value="two">
                <a class="thumbnail" id="carousel-selector-2"><img src="http://placehold.it/150x150&text=2" alt=""></a>
            </li>

            <li class="col-sm-3">
                <input type="checkbox" value="three">
                <a class="thumbnail" id="carousel-selector-3"><img src="http://placehold.it/150x150&text=3" alt=""></a>
            </li>
        </ul>
    </div>
    <%= link_to 'Eliminar imagen', new_previa_group_path(@user), class: 'btn btn-danger' %>            
    <%= link_to 'Nueva imagen', new_previa_group_path(@user), class: 'btn btn-primary' %>
  </div>
</div>

app/views/users/groups.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de grupos a las que pertenece <%= @user.first_name %></h1>
  </div>
  <div class="panel-body">

  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

    <table class="table table-bordered" aria-labelledby="tabla-grupos">
    <caption class="sr-only" id="tabla-grupos">Lista de los grupos a las que pertenece el usuario</caption>
      <thead>
        <tr>
          <th id="columna_nombre">Nombre</th>
          <th id="columna_lider">Lider</th>
          <th id="columna_activo">Activo</th>
          <th id="columna_fecha">Fecha</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @user.previa_groups.each do |previa_group| %>
          <tr>
            <td headers="columna_nombre"><%= previa_group.name %></td>
            <td headers="columna_lider"><%= previa_group.leader.first_name %></td>
            <td headers="columna_activo">
              <% if previa_group.active %>
              Si
              <% else %>
              No
              <% end %>
            </td>
            <td headers="columna_fecha"><%= previa_group.date.strftime("%d/%m/%Y") %></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-close fa-lg' aria-hidden='true'></span> Abandonar".html_safe, user_leave_group_path(previa_group),  class: "btn btn-danger", method: :post, data: { confirm: '¿Estás seguro?' } %>
              <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Integrantes".html_safe, previa_group_current_users_path(previa_group), class: "btn btn-primary" %>
              <% if previa_group.active and previa_group.leader == @user %> 
              <%= link_to "<span class='fa fa-filter fa-lg' aria-hidden='true'></span> Buscar grupos".html_safe, previa_group_search_previa_groups_path(previa_group), class: "btn btn-info" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Nuevo grupo', new_previa_group_path(@user), class: 'btn btn-primary' %>
  </div>
</div>

app/views/users/groups_leading.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de grupos que lidera <%= @user.first_name %></h1>
  </div>
  <div class="panel-body">
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

    <table class="table table-bordered" aria-labelledby="tabla-administrar">
    <caption class="sr-only" id="tabla-administrar">Lista de los grupos que administra el usuario</caption>
      <thead>
        <tr>
          <th id="columna_nombre">Nombre</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @groups_leading.each do |previa_group| %>
          <tr>
            <td headers="columna_nombre"><%= previa_group.name %></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-search fa-lg' aria-hidden='true'></span> Mostrar".html_safe, previa_group_path(previa_group), class: "btn btn-info" %>
              <%= link_to "<span class='fa fa-edit fa-lg' aria-hidden='true'></span> Editar".html_safe, edit_previa_group_path(previa_group), class: "btn btn-warning" %>
              <% if !previa_group.active %>
              <%= link_to "<span class='fa fa-hand-o-up fa-lg' aria-hidden='true'></span> Seleccionar".html_safe, previa_group_invitable_users_path(previa_group), class: "btn btn-primary" %>
              <%= link_to "<span class='fa fa-check fa-lg' aria-hidden='true'></span> Finalizar".html_safe,previa_group_finish_path(previa_group), method: :post, data: { confirm: '¿Estás seguro?' }, class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/users/inbox.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Bandeja de entrada</h1>
  </div>
  <div class="panel-body">

  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

    <table class="table table-bordered" aria-labelledby="tabla-mensajes">

    <caption class="sr-only" id="tabla-mensajes">Lista de los mensajes que recibio el usuario</caption>
      <thead>
        <tr>
          <th id="columna_destinatario">Destinatario</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @groups_leading.each do |previa_group| %>
          <tr>
            <td headers="columna_destinatario"><%= previa_group.name%></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Ver".html_safe, previa_group_inbox_path(previa_group), class: "btn btn-success" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de usuarios</h1>
  </div>
  <div class="panel-body">

  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

    <table class="table table-bordered" aria-labelledby="tabla-usuarios">
      <caption class="sr-only" id="tabla-usuarios">Lista de usuarios</caption>
        <thead>
          <tr>
            <th id="columna_nombre">Nombre</th>
            <th id="columna_apellido">Apellido</th>
            <th id="columna_mail">Mail</th>
            <th id="columna_clave">Clave</th>
            <th id="columna_fecha">Fecha de nacimiento</th>
            <th id="columna_sexo">Sexo</th>
            <th id="columna_ciudad">Ciudad</th>
            <th id="columna_acciones">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td headers="columna_nombre"><%= user.first_name %></td>
              <td headers="columna_apellido"><%= user.last_name %></td>
              <td headers="columna_mail"><%= user.email %></td>
              <td headers="columna_clave"><%= user.pass %></td>
              <td headers="columna_fecha"><%= user.birth_date %></td>
              <td headers="columna_sexo"><%= user.gender %></td>
              <td headers="columna_ciudad"><%= user.city.name %></td>
              <td headers="columna_acciones">
                <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Mostrar <span class='sr-only' aria-hidden='true'>usuario #{user.first_name} #{user.last_name}</span>".html_safe,user, class: "btn btn-success" %>
                <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Editar <span class='sr-only' aria-hidden='true'>grupo #{user.first_name} #{user.last_name}</span>".html_safe, edit_user_path(user), class: "btn btn-primary" %>
                <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Eliminar <span class='sr-only' aria-hidden='true'>grupo #{user.first_name} #{user.last_name}</span>".html_safe, user, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= link_to 'Nuevo usuario', new_user_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/users/invitations.html.erb
<% if !notice.nil? %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de invitaciones a grupos de <%= @user.first_name %></h1>
  </div>
  <div class="panel-body">
    
    <table class="table table-bordered" aria-labelledby="tabla-invitaciones">
      <caption class="sr-only" id="tabla-invitaciones">Lista de las invitaciones a grupos que recibio el usuario</caption>
      <thead>
        <tr>
          <th id="columna_grupo">Grupo</th>
          <th id="columna_lider">Lider</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @user.invitations.each do |invitation| %>
          <tr>
            <td headers="columna_grupo"><%= invitation.name %></td>
            <td headers="columna_lider"><%= invitation.leader.first_name %></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-check fa-lg' aria-hidden='true'></span> Aceptar".html_safe, user_accept_invitation_path(@user, :invitation_id => invitation.id), method: :post, data: { confirm: '¿Estás seguro?'}, class: "btn btn-success" %>
              <%= link_to "<span class='fa fa-close fa-lg' aria-hidden='true'></span> Rechazar".html_safe, user_reject_invitation_path(@user, :invitation_id => invitation.id), method: :post, data: { confirm: '¿Estás seguro?'}, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Nuevo usuario</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/notifications.html.erb
<% if !notice.nil? %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de invitaciones de <%= @user.first_name %></h1>
  </div>
  <div class="panel-body">
    

    <table class="table table-bordered" aria-labelledby="tabla-notificaciones">
    <caption class="sr-only" id="tabla-notificaciones">Lista de notificaciones que recibio el usuario</caption>
      <thead>
        <tr>
          <th id="columna_mensaje" class="col-md-9">Mensaje</th>
          <th id="columna_fecha" class="col-md-9">Fecha</th>
          <th id="columna_acciones" class="col-md-3">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @user.notifications.each do |notification| %>
          <tr>
            <td headers="columna_mensaje"><%= notification.message %></td>
            <td headers="columna_fecha"><%= notification.created_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-close fa-lg' aria-hidden='true'></span> Eliminar".html_safe, user_delete_notification_path(@user, :notification_id => notification.id), method: :post, data: { confirm: '¿Estás seguro?'}, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/previa_invitations.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de invitaciones a previa de grupos de <%= @user.first_name %></h1>
  </div>
  <div class="panel-body">
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
    
    <table class="table table-bordered" aria-labelledby="tabla-invitaciones-previa">
    <caption class="sr-only" id="tabla-invitaciones-previa">Lista de las invitaciones a previas que recibio el lider</caption>
      <thead>
        <tr>
          <th id="columna_grupo">Grupo</th>
          <th id="columna_grupo_invitado">Grupo invitado</th>
          <th id="columna_lider">Lider</th>
          <th id="columna_acciones">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @previa_invitations.each do |invitation| %>
          <tr>
            <td headers="columna_grupo"><%= invitation.inviting_group.name %></td>
            <td headers="columna_grupo_invitado"><%= invitation.invited_group.name %></td>
            <td headers="columna_lider"><%= invitation.inviting_group.leader.first_name %></td>
            <td headers="columna_acciones">
              <%= link_to "<span class='fa fa-check fa-lg' aria-hidden='true'></span> Aceptar".html_safe,previa_group_accept_previa_invitation_path(invitation.invited_group, :previa_invitation_id => invitation.id), method: :post, data: { confirm: '¿Estás seguro?'}, class: "btn btn-success" %>
              <%= link_to "<span class='fa fa-close fa-lg' aria-hidden='true'></span> Rechazar".html_safe,previa_group_reject_previa_invitation_path(invitation.invited_group, :previa_invitation_id => invitation.id), method: :post, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Datos de <%= @user.first_name %></h1>
  </div>
  <div class="panel-body">
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

  <p>
    <strong>Foto </strong>
    <%= image_tag(@user.image.thumb.url, :alt => "Imagen de perfil del usuario") if @user.image? %>
  </p>
  <p>
    <strong>Nombre </strong>
    <%= @user.first_name %>
  </p>
  <p>
    <strong>Apellido </strong>
    <%= @user.last_name %>
  </p>
  <p>
    <strong>Mail </strong>
    <%= @user.email %>
  </p>
  <p>
    <strong>Fecha de nacimiento </strong>
    <%= @user.birth_date.strftime("%d/%m/%Y") %>
  </p>
  <p>
    <strong>Sexo </strong>
    <%= @user.gender %>
  </p>
  <p>
    <strong>Ciudad </strong>
    <%= @user.city.name %>
  </p>
  <%= link_to "<span class='sr-only'>(actual)</span>Editar".html_safe, edit_user_path(@user), class: "btn btn-primary" %>
  
  </div>
</div>