config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'frontend#index'
  get 'frontend/index'

  resources :users
  post 'users/:id/accept_invitation' => 'users#accept_invitation', as: 'user_accept_invitation'
  post 'users/:id/reject_invitation' => 'users#reject_invitation', as: 'user_reject_invitation'
  get 'users/:id/invitations' => 'users#invitations', as: 'user_invitations'
  get 'users/:id/groups' => 'users#groups', as: 'user_groups'
  post 'users/:id/ban_group' => 'users#ban_group', as: 'user_ban_group'
  post 'users/login' => 'users#login', as: 'user_login'
  post 'users/logout' => 'users#logout', as: 'user_logout'
  get 'users/:id/groups_leading' => 'users#groups_leading', as: 'user_groups_leading'
  post 'users/:id/leave_group' => 'users#leave_group', as: 'user_leave_group'
  get 'users/:id/previa_invitations' => 'users#previa_invitations', as: 'user_previa_invitations'
  get 'users/:id/inbox' => 'users#inbox', as: 'user_inbox'
  get 'users/:id/gallery' => 'users#gallery', as: 'user_gallery'
  get 'users/:id/edit_gallery' => 'users#edit_gallery', as: 'user_edit_gallery'
  get 'users/:id/notifications' => 'users#notifications', as: 'user_notifications'
  post 'users/:id/delete_notification' => 'users#delete_notification', as: 'user_delete_notification'
  

  resources :previa_groups
  post 'previa_groups/:id/invite_user' => 'previa_groups#invite_user', as: 'previa_group_invite_user'
  get 'previa_groups/:id/invitable_users' => 'previa_groups#invitable_users', as: 'previa_group_invitable_users'
  post 'previa_groups/:id/ban_group' => 'previa_groups#ban_group', as: 'previa_group_ban_group'
  post 'previa_groups/:id/invite_group' => 'previa_groups#invite_group', as: 'previa_group_invite_group'
  post 'previa_groups/:id/accept_previa_invitation' => 'previa_groups#accept_previa_invitation', as: 'previa_group_accept_previa_invitation'
  post 'previa_groups/:id/reject_previa_invitation' => 'previa_groups#reject_previa_invitation', as: 'previa_group_reject_previa_invitation'
  get 'previa_groups/:id/current_users' => 'previa_groups#current_users', as: 'previa_group_current_users'
  post 'previa_groups/:id/finish' => 'previa_groups#finish', as: 'previa_group_finish'
  get 'previa_groups/:id/details' => 'previa_groups#details', as: 'previa_group_details'
  get 'previa_groups/:id/search_previa_groups' => 'previa_groups#search_previa_groups', as: 'previa_group_search_previa_groups'
  get 'previa_groups/:id/inbox' => 'previa_groups#inbox', as: 'previa_group_inbox'
  get 'previa_groups/:id/chat' => 'previa_groups#chat', as: 'previa_group_chat'
  post 'previa_groups/:id/send_message' => 'previa_groups#send_message', as: 'previa_group_send_message'
  post 'previa_groups/:id/delete_user' => 'previa_groups#delete_user', as: 'previa_group_delete_user'

  resources :properties
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :previa_group_properties
  has_many :previa_groups, :through => :previa_group_properties
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @title = "Propiedades"
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @title = "Propiedad"
  end

  # GET /properties/new
  def new
    @title = "Nueva propiedad"
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
    @title = "Editar propiedad"
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'La propiedad fue creada con éxito.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'La propiedad fue modificada con éxito.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'La propiedad fue borrada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.fetch(:property, {})
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editar propiedad</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @property, class: "btn btn-success" %> 
<%= link_to 'Atrás', properties_path, class: 'btn btn-info btn-lg' %>

app/views/properties/index.html.erb
<% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

<h1>Lista de propiedades</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Mostrar <span class='sr-only' aria-hidden='true'>propiedad #{property.name}</span>".html_safe,property, class: "btn btn-success" %>
        <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Editar <span class='sr-only' aria-hidden='true'>propiedad #{property.name}</span>".html_safe, edit_property_path(property), class: "btn btn-primary" %>
        <%= link_to "<span class='fa fa-navicon fa-lg' aria-hidden='true'></span> Eliminar <span class='sr-only' aria-hidden='true'>propiedad #{property.name}</span>".html_safe, property, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva propiedad', new_property_path, class: 'btn btn-primary' %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Editar', edit_property_path(@property), class: "btn btn-primary" %> |
<%= link_to 'Atrás', properties_path, class: 'btn btn-info btn-lg' %>